# Generated by Django 5.2.1 on 2025-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='total_borrowings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='total_returns',
            field=models.IntegerField(default=0),
        ),
    ]
