# Generated by Django 5.2.1 on 2025-05-15 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_total_borrowings_users_total_returns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='total_borrowings',
        ),
        migrations.RemoveField(
            model_name='users',
            name='total_returns',
        ),
    ]
