
# Generated by Django 5.2.1 on 2025-05-16 13:29

# Generated by Django 5.2.1 on 2025-05-16 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_users_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
