# Generated by Django 5.2.1 on 2025-05-19 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_users_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='total_returns',
        ),
    ]
