# Generated by Django 5.2.1 on 2025-05-16 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_cover_image_book_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='images',
        ),
    ]
