# Generated by Django 5.2.1 on 2025-05-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_image_book_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='images',
            new_name='image',
        ),
    ]
