# Generated by Django 5.2.1 on 2025-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowings',
        ),
    ]
