# Generated by Django 5.2.1 on 2025-05-17 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
